<div class="container-fluid">
<ol class="breadcrumb">
        <li class="breadcrumb-item">
            <?php 
                echo $this->tag->linkTo([
                    "usuario",
                    'Usuarios'
                    ]); 
            ?>
        </li>
        <li class="breadcrumb-item active">Editar usuario</li>
    </ol>

<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>



<div class="page-header">
    <h3>
        Editar usuario
    </h3>


            <?php echo $this->getContent(); ?>

            <?php
                echo $this->tag->form(
                    [
                        "usuario/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal"
                    ]
                );
            ?>

            <div class="form-group">
                <label for="fieldTipodocumento" class="col-sm-2 control-label">Tipo documento</label>
                <div class="col-sm-5">
                <?php
                        echo $this->tag->select(array("idPerfil",
                                                        AdmTipoDocumento::Find(),
                                                        "class" => "form-control",
                                                        "using" => ['idTipoDocumento','nombreTipoDocumento'],));
                   ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldDocumento" class="col-sm-2 control-label">Documento</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["documento", "size" => 30, "class" => "form-control", "id" => "fieldDocumento"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldPrimernombre" class="col-sm-2 control-label">Primer nombre</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["primerNombre", "size" => 30, "class" => "form-control", "id" => "fieldPrimernombre"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldSegundonombre" class="col-sm-2 control-label">Segundo nombre</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["segundoNombre", "size" => 30, "class" => "form-control", "id" => "fieldSegundonombre"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldPrimerapellido" class="col-sm-2 control-label">Primer apellido</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["primerApellido", "size" => 30, "class" => "form-control", "id" => "fieldPrimerapellido"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldSegundoapellido" class="col-sm-2 control-label">Segundo apellido</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["segundoApellido", "size" => 30, "class" => "form-control", "id" => "fieldSegundoapellido"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldDireccion" class="col-sm-2 control-label">Dirección</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["direccion", "size" => 30, "class" => "form-control", "id" => "fieldDireccion"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldGenero" class="col-sm-2 control-label">Género</label>
                <div class="col-sm-5">
                <?php
                        echo $this->tag->select(array("idPerfil",
                                                        AdmGenero::Find(),
                                                        "class" => "form-control",
                                                        "using" => ['idGenero','nombreGenero'],));
                   ?>                </div>
            </div>

            <div class="form-group">
                <label for="fieldCorreo" class="col-sm-2 control-label">Correo</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["correo", "size" => 30, "class" => "form-control", "id" => "fieldCorreo"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldTelefono" class="col-sm-2 control-label">Teléfono</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["telefono", "size" => 30, "class" => "form-control", "id" => "fieldTelefono"]) ?>
                </div>
            </div>

            

            <div class="form-group">
                <label for="fieldFechanacimiento" class="col-sm-2 control-label">Fecha nacimiento</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["fechaNacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechanacimiento"]) ?>
                </div>
            </div>

            

            <div class="form-group">
                <label for="fieldPerfil" class="col-sm-2 control-label">Perfil</label>
                <div class="col-sm-5">
                    <?php
                        echo $this->tag->select(array("idPerfil",
                                                        AdmPerfil::Find(),
                                                      "class" => "form-control",
                                                      "using" => ['idPerfil','nombrePerfil'],));
                   ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldFechacreacion" class="col-sm-2 control-label">Fecha creación</label>
                <div class="col-sm-5">
                    <?php echo $this->tag->textField(["fechaCreacion", "size" => 30, "class" => "form-control", "id" => "fieldFechacreacion", "disabled" => "disabled"]) ?>
                </div>
            </div>


            <?php echo $this->tag->hiddenField("id") ?>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-primary"]) ?>
                </div>
            </div>
</div>

<?php echo $this->tag->endForm(); ?>
