<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["usuario", "Atras"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Creación de usuarios
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "usuario/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTipodocumento" class="col-sm-2 control-label">Tipo documento</label>
    <div class="col-sm-5">
            <?php
            $tipodocumento = AdmTipoDocumento::find();
            echo $this->tag->select([
                'tipoDocumento',
                $tipodocumento,
                'using' => ['idTipoDocumento','nombreTipoDocumento',],
                'class' => 'form-control',
                'useEmpty' => true,
                'emptyText' => 'Elija un tipo de documento'
            ])?>
    </div>
</div>


<div class="form-group">
    <label for="fieldDocumento" class="col-sm-2 control-label">Documento</label>
    <div class="col-sm-5">
        <?php echo $this->tag->numericField(["documento", "size" => 30, "class" => "form-control", "id" => "fieldDocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrimernombre" class="col-sm-2 control-label">Primer nombre</label>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(["primerNombre", "size" => 30, "class" => "form-control", "id" => "fieldPrimernombre"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSegundonombre" class="col-sm-2 control-label">Segundo nombre</label>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(["segundoNombre", "size" => 30, "class" => "form-control", "id" => "fieldSegundonombre"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrimerapellido" class="col-sm-2 control-label">Primer apellido</label>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(["primerApellido", "size" => 30, "class" => "form-control", "id" => "fieldPrimerapellido"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSegundoapellido" class="col-sm-2 control-label">Segundo apellido</label>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(["segundoApellido", "size" => 30, "class" => "form-control", "id" => "fieldSegundoapellido"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDireccion" class="col-sm-2 control-label">Direccion</label>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(["direccion", "size" => 30, "class" => "form-control", "id" => "fieldDireccion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGenero" class="col-sm-2 control-label">Genero</label>
    <div class="col-sm-5">
        <?php
            $genero = AdmGenero::find();
            echo $this->tag->select([
                'genero',
                $genero,
                'using' => ['idGenero','nombreGenero'],
                'class' => 'form-control',
                'useEmpty' => true,
                'emptyText' =>'Elija un género'
            ])
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCorreo" class="col-sm-2 control-label">Correo</label>
    <div class="col-sm-5">
        <?php echo $this->tag->emailField(["correo", "size" => 30, "class" => "form-control", "id" => "fieldCorreo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTelefono" class="col-sm-2 control-label">Teléfono</label>
    <div class="col-sm-5">
        <?php echo $this->tag->numericField(["telefono", "size" => 30, "class" => "form-control", "id" => "fieldTelefono"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldContrasena" class="col-sm-2 control-label">Contraseña</label>
    <div class="col-sm-5">
        <?php echo $this->tag->passwordField(["contrasena", "size" => 30, "class" => "form-control", "id" => "fieldContrasena"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechanacimiento" class="col-sm-2 control-label">Fecha nacimiento</label>
    <div class="col-sm-5">
        <?php echo $this->tag->dateField(["fechaNacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechanacimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-5">
        <?php
            $estado = UsuarioEstado::find();
            echo $this->tag->select([
                'estado',
                $estado,
                'useEmpty' => true,
                'using' => ['idEstado', 'nombreEstado'],
                 'class' => "form-control", 
                 'emptyText' => 'Elija un estado'
            ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPerfil" class="col-sm-2 control-label">Perfil</label>
    <div class="col-sm-5">
        <?php 
            $perfil = AdmPerfil::find();
        echo $this->tag->select([
            'perfil', 
            $perfil, 
            'class' => "form-control", 
            'using' => ['idPerfil','nombrePerfil'],
            'useEmpty' => true,
            'emptyText' => 'Elija un tipo de perfil para el usuario'
            ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechacreacion" class="col-sm-2 control-label">Fecha creacion</label>
    <div class="col-sm-5">
        <?php echo $this->tag->dateField(["fechaCreacion", "size" => 30, "class" => "form-control", "id" => "fieldFechacreacion"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-primary"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
