<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="next"><?php echo $this->tag->linkTo(["usuario/new", "Crear "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Listado de usuarios</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                   
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>Estado</th>
            <th>Perfil</th>
            <th>FechaCreacion</th>

                <th></th>
               
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
            
            <td><?php echo $usuario->primerNombre ?></td>
            <td><?php echo $usuario->primerApellido ?></td>
            <td><?php echo $usuario->correo ?></td>
            <td><?php echo $usuario->UsuarioEstado->nombreEstado ?></td>
            <td><?php echo $usuario->AdmPerfil->nombrePerfil ?></td>
            <td><?php echo $usuario->fechaCreacion ?></td>

                <td><?php echo $this->tag->linkTo(["usuario/edit/" . $usuario->idUsuario, "Editar"]); ?></td>
                
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
