<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["usuario/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["usuario/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>IdUsuario</th>
            <th>TipoDocumento</th>
            <th>Documento</th>
            <th>PrimerNombre</th>
            <th>SegundoNombre</th>
            <th>PrimerApellido</th>
            <th>SegundoApellido</th>
            <th>Direccion</th>
            <th>Genero</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th>Contrasena</th>
            <th>FechaNacimiento</th>
            <th>Estado</th>
            <th>Perfil</th>
            <th>FechaCreacion</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
                <td><?php echo $usuario->idUsuario ?></td>
            <td><?php echo $usuario->tipoDocumento ?></td>
            <td><?php echo $usuario->documento ?></td>
            <td><?php echo $usuario->primerNombre ?></td>
            <td><?php echo $usuario->segundoNombre ?></td>
            <td><?php echo $usuario->primerApellido ?></td>
            <td><?php echo $usuario->segundoApellido ?></td>
            <td><?php echo $usuario->direccion ?></td>
            <td><?php echo $usuario->genero ?></td>
            <td><?php echo $usuario->correo ?></td>
            <td><?php echo $usuario->telefono ?></td>
            <td><?php echo $usuario->contrasena ?></td>
            <td><?php echo $usuario->fechaNacimiento ?></td>
            <td><?php echo $usuario->estado ?></td>
            <td><?php echo $usuario->perfil ?></td>
            <td><?php echo $usuario->fechaCreacion ?></td>

                <td><?php echo $this->tag->linkTo(["usuario/edit/" . $usuario->idUsuario, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["usuario/delete/" . $usuario->idUsuario, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
