<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <?php 
                echo $this->tag->linkTo([
                    "index",
                    'Dashboard'
                    ]); 
            ?>
        </li>
        <li class="breadcrumb-item active">Usuarios</li>
    </ol>

    <?php
    /**
     * @var \Phalcon\Mvc\View\Engine\Php $this
     */
    ?>

    <?php use Phalcon\Tag; ?>
<!--
    <div class="row">
        <nav>
            <ul class="pager">
                <li class="next">
                <?php //echo $this->tag->linkTo(["usuario/new", "Crear "]); ?></li>
            </ul>
        </nav>
    </div>
-->


    <div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i> Listado de usuarios</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Tiger Nixon</td>
                        <td>System Architect</td>
                        <td>Edinburgh</td>
                        <td>61</td>
                        <td>2011/04/25</td>
                        <td>$320,800</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted"><?php echo $this->tag->linkTo(["usuario/new", "Crear "]); ?></div>
</div>








<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                   
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>Estado</th>
            <th>Perfil</th>
            <th>FechaCreacion</th>

                <th></th>
               
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
            
            <td><?php echo $usuario->primerNombre ?></td>
            <td><?php echo $usuario->primerApellido ?></td>
            <td><?php echo $usuario->correo ?></td>
            <td><?php echo $usuario->UsuarioEstado->nombreEstado ?></td>
            <td><?php echo $usuario->AdmPerfil->nombrePerfil ?></td>
            <td><?php echo $usuario->fechaCreacion ?></td>

                <td><?php echo $this->tag->linkTo(["usuario/edit/" . $usuario->idUsuario, "Editar"]); ?></td>
                
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
</div>