<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["adm_tipo_documento", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit adm_tipo_documento
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "adm_tipo_documento/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombretipodocumento" class="col-sm-2 control-label">NombreTipoDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreTipoDocumento", "size" => 30, "class" => "form-control", "id" => "fieldNombretipodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIniciales" class="col-sm-2 control-label">Iniciales</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["iniciales", "size" => 30, "class" => "form-control", "id" => "fieldIniciales"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
