<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search adm_tipo_documento
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["adm_tipo_documento/new", "Create adm_tipo_documento"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "adm_tipo_documento/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdtipodocumento" class="col-sm-2 control-label">IdTipoDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idTipoDocumento", "type" => "number", "class" => "form-control", "id" => "fieldIdtipodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombretipodocumento" class="col-sm-2 control-label">NombreTipoDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreTipoDocumento", "size" => 30, "class" => "form-control", "id" => "fieldNombretipodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIniciales" class="col-sm-2 control-label">Iniciales</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["iniciales", "size" => 30, "class" => "form-control", "id" => "fieldIniciales"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
