<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["paciente", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit paciente
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "paciente/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTipodocumento" class="col-sm-2 control-label">TipoDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipoDocumento", "type" => "number", "class" => "form-control", "id" => "fieldTipodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechanacimiento" class="col-sm-2 control-label">FechaNacimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaNacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechanacimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDocumento" class="col-sm-2 control-label">Documento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["documento", "size" => 30, "class" => "form-control", "id" => "fieldDocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrimernomber" class="col-sm-2 control-label">PrimerNombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["primerNombre", "size" => 30, "class" => "form-control", "id" => "fieldPrimernomber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSegundonombre" class="col-sm-2 control-label">SegundoNombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["segundoNombre", "size" => 30, "class" => "form-control", "id" => "fieldSegundonombre"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrimerapellido" class="col-sm-2 control-label">PrimerApellido</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["primerApellido", "size" => 30, "class" => "form-control", "id" => "fieldPrimerapellido"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSegundoapellido" class="col-sm-2 control-label">SegundoApellido</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["segundoApellido", "size" => 30, "class" => "form-control", "id" => "fieldSegundoapellido"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGenero" class="col-sm-2 control-label">Genero</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["genero", "type" => "number", "class" => "form-control", "id" => "fieldGenero"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDireccion" class="col-sm-2 control-label">Direccion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["direccion", "size" => 30, "class" => "form-control", "id" => "fieldDireccion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTelefono" class="col-sm-2 control-label">Telefono</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["telefono", "size" => 30, "class" => "form-control", "id" => "fieldTelefono"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCelular" class="col-sm-2 control-label">Celular</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["celular", "size" => 30, "class" => "form-control", "id" => "fieldCelular"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEps" class="col-sm-2 control-label">Eps</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["eps", "type" => "number", "class" => "form-control", "id" => "fieldEps"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMunicipio" class="col-sm-2 control-label">Municipio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["municipio", "type" => "number", "class" => "form-control", "id" => "fieldMunicipio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZona" class="col-sm-2 control-label">Zona</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zona", "type" => "number", "class" => "form-control", "id" => "fieldZona"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRegimen" class="col-sm-2 control-label">Regimen</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["regimen", "type" => "number", "class" => "form-control", "id" => "fieldRegimen"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTipoafiliacion" class="col-sm-2 control-label">TipoAfiliacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipoAfiliacion", "type" => "number", "class" => "form-control", "id" => "fieldTipoafiliacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldParentezco" class="col-sm-2 control-label">Parentezco</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["parentezco", "type" => "number", "class" => "form-control", "id" => "fieldParentezco"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRangosalarial" class="col-sm-2 control-label">RangoSalarial</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rangoSalarial", "type" => "number", "class" => "form-control", "id" => "fieldRangosalarial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaingreso" class="col-sm-2 control-label">FechaIngreso</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaIngreso", "size" => 30, "class" => "form-control", "id" => "fieldFechaingreso"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
