<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <?php
                echo $this->tag->linkTo([
                    "index",
                    '<i class="fas fa-fw fa-tachometer-alt"></i> Dashboard'
                    ]);
            ?>
        </li>
        <li class="breadcrumb-item active"><i class="fas fa-user-cog"></i> <span>Perfiles</span></li>
    </ol>

    <?php
    /**
     * @var \Phalcon\Mvc\View\Engine\Php $this
     */
    ?>
     <div class="collapse m-2" id="collapseExample">
        <div class="card card-body">
                <?php $this->partial('usuario/index'); ?>
        </div>
    </div>

<?php use Phalcon\Tag; ?>





<?php echo $this->getContent(); ?>
<div class="card mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                     <h5><i class="fas fa-table"></i> Listado de perfiles</h5>
                </div>
                <div class="col-md-3 text-right">
                        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                            <i class="fas fa-filter"></i> Filtros
                        </button>
                            <?php
                                echo $this->tag->linkTo(["usuario/new", "<i class='fas fa-plus-square'></i> <span>Crear paciente</span>", "class" => "btn btn-success text-rigth"]);
                            ?>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
            <tr>
                
            <th class="text-center">Nombre Perfil</th>
            <th class="text-center">Descripción </th>

                <th class="text-center">Acción</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $adm_perfil): ?>
            <tr>
            
            <td class="text-center"><?php echo $adm_perfil->nombrePerfil ?></td>
            <td class="text-center"><?php echo $adm_perfil->descPerfil ?></td>
            <td class="text-center"><?php echo $this->tag->linkTo(["adm_perfil/edit/" . $adm_perfil->idPerfil, "<i class='fas fa-pencil-alt'></i>" , "class" => "btn btn-warning btn-sm"]); ?></td>

                
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("adm_perfil/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("adm_perfil/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("adm_perfil/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("adm_perfil/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
