<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["paciente_rango_salarial", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit paciente_rango_salarial
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "paciente_rango_salarial/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombrerangosalarial" class="col-sm-2 control-label">NombreRangoSalarial</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreRangoSalarial", "size" => 30, "class" => "form-control", "id" => "fieldNombrerangosalarial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPorcentaje" class="col-sm-2 control-label">Porcentaje</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["porcentaje", "size" => 30, "class" => "form-control", "id" => "fieldPorcentaje"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
