<?php echo $this->tag->form([
    "sesion/sesion"
]);
?>  
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <!--<h5 class="card-title text-center font-weight-bold">CenpiClinic </h5>-->
                    <img src="<?php echo $this->url->get('img/Logo_Cenpi.png')?>" >
                    <h6 class="card-title text-center"><span class="font-weight-light">Inicio de Sesion</span></h6>
                    <form class="form-signin">
                        <div class="form-label-group">
                            <?php 
                                echo $this->tag->emailField(array("email",         
                                "placeholder" => "Correo electrónico",
                                "class" => "form-control", 
                                "required" => "true",
                                "autofocus" => "true",
                                "id" => "inputEmail"
                                )) 
                            ?>
                            <label for="inputEmail">Correo Electronico</label>
                        </div>
                        <div class="form-label-group">
                            <?php 
                                echo $this->tag->passwordField(array("contrasena",                        
                                    "placeholder" => "Contraseña",
                                    "class" => "form-control", 
                                    "required" => "true",
                                    "type" => "password",
                                    "id" => "inputPassword"
                                ))
                            ?>
                            <label for="inputPassword">Contraseña</label>
                        </div>
                        <?php 
                            echo $this->tag->submitButton(
                                [  
                                    "Ingresar",
                                    'class' => 'btn btn-lg btn-primary btn-block text-uppercase',
                                    "type" => "submit"
                                ]
                            ); 
                        ?>
                        <?php 
                            echo $this->tag->linkTo(
                                [  
                                    "index",
                                    "Cancelar",
                                    'class' => 'btn btn-lg btn-warning btn-block text-uppercase',
                                    "type" => "submit"

                                ]
                            ); 
                        ?>
                    </form>
                    <div class="m-2">
                        <?php echo $this->getContent();?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
