
<h1><center>Cenpi Clinic</center></h1>

<?php echo $this->tag->form([
    "sesion/sesion"
]);
?>


<div class="container">
     <div class="card ">
        <div class="content" align="center">
            <h4 class="title">Iniciar sesión</h4>
            <div class="row">
                <div class="col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">
                    <div class="mk-m-b-10">
                        <?php echo $this->tag->emailField(array("email",
                         
                         "placeholder" => "Correo electrónico",
                          "class" => "form-control", 
                          )) ?>
                    </div>
                    <br>
                    <div class="mk-m-b-10">
                        <?php echo $this->tag->passwordField(array("contrasena",
                        
                         "placeholder" => "Contraseña",
                         "class" => "form-control", 
                         )) ?>
                    </div>
                </div>
            </div>

                        <div class="container">
                                <div class="col-md-4 col-lg-offset-2">
                                    <?php echo $this->tag->submitButton(
                                    [  
                                        "Ingresar",
                                        'class' => 'btn btn-primary'

                                    ]); ?>

                                    <?php echo $this->tag->linkTo(
                                    [  
                                        "index",
                                        "Cancelar",
                                        'class' => 'btn btn-warning'

                                    ]); ?>
                                </div>
                        </div>                        

            <br>
           
        </div>
    </div>
</div>
                                    </form>
<?php echo $this->getContent(); ?>


