<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search usuario_estado
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["usuario_estado/new", "Create usuario_estado"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "usuario_estado/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdestado" class="col-sm-2 control-label">IdEstado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idEstado", "type" => "number", "class" => "form-control", "id" => "fieldIdestado"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreestado" class="col-sm-2 control-label">NombreEstado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreEstado", "size" => 30, "class" => "form-control", "id" => "fieldNombreestado"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescestado" class="col-sm-2 control-label">DescEstado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descEstado", "size" => 30, "class" => "form-control", "id" => "fieldDescestado"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
