<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search adm_tipoExamen
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["adm_tipoExamen/new", "Create adm_tipoExamen"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "adm_tipoExamen/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdtipoexamen" class="col-sm-2 control-label">IdTipoExamen</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idTipoExamen", "type" => "number", "class" => "form-control", "id" => "fieldIdtipoexamen"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreexamen" class="col-sm-2 control-label">NombreExamen</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreExamen", "size" => 30, "class" => "form-control", "id" => "fieldNombreexamen"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesctipoexamen" class="col-sm-2 control-label">DescTipoExamen</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descTipoExamen", "size" => 30, "class" => "form-control", "id" => "fieldDesctipoexamen"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
