<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <?php
                echo $this->tag->linkTo([
                    "index",
                    '<i class="fas fa-fw fa-tachometer-alt"></i> Dashboard'
                    ]);
            ?>
        </li>
        <li class="breadcrumb-item active"><i class="fas fa-user-cog"></i> <span>Tipos de examen</span></li>
    </ol>

    <?php
    /**
     * @var \Phalcon\Mvc\View\Engine\Php $this
     */
    ?>
     <div class="collapse m-2" id="collapseExample">
        <div class="card card-body">
                <?php $this->partial('usuario/index'); ?>
        </div>
    </div>

<?php use Phalcon\Tag; ?>





<?php echo $this->getContent(); ?>
<div class="card mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                     <h5><i class="fas fa-table"></i> Listado de examenes</h5>
                </div>
                <div class="col-md-3 text-right">
                        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                            <i class="fas fa-filter"></i> Filtros
                        </button>
                            <?php
                                echo $this->tag->linkTo(["adm_tipoExamen/new", "<i class='fas fa-plus-square'></i> <span>Crear tipo examen</span>", "class" => "btn btn-success text-rigth"]);
                            ?>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
            <tr>
            <th class="text-center">Nombre Examen</th>
            <th class="text-center">Descripción </th>

                <th class="text-center">Acción</th>
                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $adm_tipoExamen): ?>
            <tr>
            <td class="text-center"><?php echo $adm_tipoExamen->nombreExamen ?></td>
            <td class="text-center"><?php echo $adm_tipoExamen->descTipoExamen ?></td>
            <td class="text-center"><?php echo $this->tag->linkTo(["adm_tipoExamen/edit/" . $adm_tipoExamen->idTipoExamen, "<i class='fas fa-pencil-alt'></i>" , "class" => "btn btn-warning btn-sm"]); ?></td>

                
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="card-footer small text-muted">
            <div class="row">
                <div class="col-md-1 p-2 mb-1 bg-danger text-white"><b>Usuarios Anulados</b></div>
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group mr-2" role="group" aria-label="First group">
                            <?php echo $this->tag->linkTo(["adm_tipoExamen/search", "Primero", "class" => "btn btn-outline-primary"]) ?>
                            <?php echo $this->tag->linkTo(["adm_tipoExamen/search?page=" . $page->before, "Anterior", "class" => "btn btn-outline-primary"]) ?>
                            <?php echo $this->tag->linkTo(["adm_tipoExamen/search?page=" . $page->next, "Siguiente", "class" => "btn btn-outline-primary"]) ?>
                            <?php echo $this->tag->linkTo(["adm_tipoExamen/search?page=" . $page->last, "Último", "class" => "btn btn-outline-primary"]) ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <h6 class="text-right">
                        <?php echo $page->current, " / ", $page->total_pages ?>
                    </h6>
                </div>
            </div>
        </div>
