<div class="container-fluid">
<ol class="breadcrumb">
        <li class="breadcrumb-item">
            <?php 
                echo $this->tag->linkTo([
                    "index",
                    '<i class="fas fa-fw fa-tachometer-alt"></i> Dashboard'
                    ]); 
            ?>
        </li>
        <li class="breadcrumb-item">
            <?php 
                echo $this->tag->linkTo([
                    "usuario",
                    '<i class="fas fa-user-cog"></i> Usuarios'
                    ]); 
            ?>
        </li>
        <li class="breadcrumb-item active"><i class="fas fa-user-plus"></i> Creación de EPS</li>
    </ol>

<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "adm_eps/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                    <h3 class="card-title">Crear nueva EPS </h3>
                    <hr>
            </div>
            
            <div class="card-body">
                <form>                                        
                    <div class="row">
                        <div class="form-group">
                            <label for="fieldNiteps" class="col-sm-2 control-label">Nit</label>
                            <div class="col-sm-10">
                                <?php echo $this->tag->textField(["nitEps", "size" => 30, "class" => "form-control", "id" => "fieldNiteps"]) ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fieldNombreeps" class="col-sm-4 control-label">Nombre</label>
                            <div class="col-sm-10">
                                <?php echo $this->tag->textField(["nombreEps", "size" => 30, "class" => "form-control", "id" => "fieldNombreeps"]) ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>                          </div>
                                </div>
                    </div>
                    </div>
                </form>                    
            </div>
        </div>                   
</div>






<?php echo $this->tag->endForm(); ?>
