<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> Cenpi Clinic</title>
        <?php 
            $this->assets->outputCss('headercss'); 
        ?>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <?php 
            if($this->session->get('auth')){ 
        ?>
        <nav class="navbar navbar-expand navbar-dark bg-dark static-top fixed-top">
            <a class="navbar-brand mr-1" href="index.html"><img src="<?php echo $this->url->get('img/Logo_Cenpi.png')?>"></a>
            <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars"></i>
            </button>
            <!-- Navbar Search -->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                <!--   
                    <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div> 
                -->
                </div>
            </form>

            <!-- Navbar -->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">9+</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span class="badge badge-danger">7</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <?php echo $this->tag->linkTo([
                        "sesion/logout",
                        'Cerrar sesión',
                        "class" => "dropdown-item"
                        ]);
                    ?>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="wrapper" style="margin-top:58px">
            <!-- Sidebar -->
            <ul class="sidebar navbar-nav">
                                <!--
                <li class="nav-item active">
                    <a class="nav-link" href="index.html">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-fw fa-folder"></i>
                        <span>Pages</span>
                    </a>
                    
                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                        <h6 class="dropdown-header">Login Screens:</h6>
                        <a class="dropdown-item" href="login.html">Login</a>
                        <a class="dropdown-item" href="register.html">Register</a>
                        <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
                        <div class="dropdown-divider"></div>
                        <h6 class="dropdown-header">Other Pages:</h6>
                        <a class="dropdown-item" href="404.html">404 Page</a>
                        <a class="dropdown-item" href="blank.html">Blank Page</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="charts.html">
                        <i class="fas fa-fw fa-chart-area"></i>
                        <span>Charts</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tables.html">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Tables</span></a>
                </li>                -->
                <?php 
                    $user = $this->session->get('auth'); 
                    if( $user['rol'] === 'Administrador' OR 'Call center' ) {
                ?>
                <li class="nav-item">
                    <?php 
                        echo $this->tag->linkTo([
                            "index",
                            '<i class="fas fa-fw fa-tachometer-alt"></i> <span>Dashboard</span>',
                            "class" => "nav-link"
                            ]); 
                    ?>
                </li>
                <?php }                            
                    if( $user['rol'] === 'Administrador' ){
                ?>
                <li class="nav-item">
                    <?php 
                        echo $this->tag->linkTo([
                            "usuario/search",
                            '<i class="fas fa-user-cog"></i> <span>Usuarios</span>',
                            "class" => "nav-link"
                            ]); 
                    ?>
                </li>
                <li class="nav-item">
                    <?php 
                        echo $this->tag->linkTo([
                            "index",
                            '<i class="fas fa-book"></i> <span>Historia clínica</span>',
                            "class" => "nav-link"
                            ]); 
                    ?>
                </li>
                <?php } ?>
            </ul>       
            <div id="content-wrapper">
                <div class="container-fluid">
                    <?php echo $this->getContent(); ?>
                </div>
                <footer class="sticky-footer">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright © Your Website 2018</span>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <?php 
            }else{  
                echo $this->getContent(); 
            } 
            $this->assets->outputJs('headerjs'); 
        ?>       
    </body>
</html>